
services:
  rag-api:
    build: .
    image: rag-bot:latest
    env_file:
      - .env
    environment:
      RUN_MODE: api
      LOG_TO_STDOUT: "true"
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/logs
      - hf-cache:/app/.cache/huggingface
    command: ["python", "run.py"]

  discord-bot:
    image: rag-bot:latest
    env_file:
      - .env
    environment:
      RUN_MODE: bot
      LOG_TO_STDOUT: "true"
    depends_on:
      - rag-api
    volumes:
      - logs:/app/logs
      - hf-cache:/app/.cache/huggingface
    profiles:
      - bot
    command: ["python", "run.py"]

volumes:
  logs:
  hf-cache:
